# Generated by Django 4.2.5 on 2025-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('examples', models.TextField()),
            ],
        ),
    ]
