# Generated by Django 4.2.5 on 2025-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilers',
            name='message',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='compilers',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
